spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/docgdb1?currentSchema=userschema
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
      default_schema: userschema
      defer-datasource-initialization: true
server:
  port: 8082
  servlet:
    context-path: /docg/v1
